spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtsecurity
    username: postgres
    password: sahar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database_platform: org.hibernate.dialect.PostgreSQLDialect
